name: Run playwright tests
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Run-Playwright-tests:
      environment:  testing
      runs-on:  ubuntu-latest
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      steps:
        - name: Checkout repository code
          uses: actions/checkout@v3
        - name: Install Playwright dependencies
          run:  npm ci
        - name: Install Playright browsers
          run:  npx playwright install chromium --with-deps
        - name: Run tests
          run:  npx playwright test
        - name: Generate Allure report
          if: ${{ !cancelled() }}
          run: npx allure-commandline generate allure-results --clean -o allure-report

        - name: Upload Allure report
          if: ${{ !cancelled() }}
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: allure-report
            retention-days: 30

